### ISSUE TITLE
회원/마이페이지 기능 2차 MVP개발

### ISSUE THREAD

**Issue by pangyosim** [DevCVTeam/DevCV-backend#44]
## 어떤 기능인가요?
> RESTful에 맞게 API 요청부분 수정, 회원기능 응답값 수정, 예외처리 수정, refreshToken 기능 로직구현

## 작업 상세 내용
- [x] 회원로그, refreshToken 로직 추가 구현
- [x] 예외처리보완
- [x] API 요청부분 수정
- [x] 회원기능 응답값 수정

**Comment by toris-dev** [comment]
auth/config/CorsConfig.java 코드에서 아래와 같이 수정해야 할 것 같습니다!

/member/* API 가 동작하지 않길래 docker log 훓어보니 아래와 같은 에러가 떴습니다.

```shell
java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value "*" since that cannot be set on the "Access-Control-Allow-Origin" response header. To allow credentials to a set of origins, list them explicitly or consider using "allowedOriginPatterns" instead.
```

![image](https://github.com/DevCVTeam/DevCV-backend/assets/66780368/48292c38-56ea-46ad-a848-ef31bb4331a1)

### 코드 수정해야 할 부분
auth/config/CorsConfig.java 15번 라인
```java
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*"); // -> setAllowCredentials(true) 와 addAllowedOrigin("*") 을 동시에 사용할 수 없도록 변경되었답니다. 
        // config.addAllowedOriginPattern("*"); 수정해야합니다.
```

**Comment by pangyosim** [comment]
넵 확인했습니다.
제가 바뀐 version에 따라 바뀌었는데 미처 확인을 못했네요,,
PR #45 부분에 함께 적용시켜놓겠습니다~🙂
