### ISSUE TITLE
다른 서비스에서 resume를 생성할 수 없음

### ISSUE THREAD

**Issue by taehyeonn** [DevCVTeam/DevCV-backend#48]
## 어떤 버그인가요?
> resumeId로 resume를 생성할 수 없음

## 어떤 상황에서 발생한 버그인가요?
> (가능하면) Given-When-Then 형식으로 서술해주세요

![스크린샷 2024-06-19 오후 12 56 25](https://github.com/DevCVTeam/DevCV-backend/assets/143480682/e8fbff95-77f3-448f-bd76-f74160ead9a8)

order 도메인에서 resumeId를 입력받아 resume 객체를 생성해야 하는 상황

resume service에서 resumeId로 resume를 생성하는 메서드를 지원하지 않음

![스크린샷 2024-06-19 오후 12 43 52](https://github.com/DevCVTeam/DevCV-backend/assets/143480682/64f3ac73-8950-459e-9c97-8e177e49d94f)
findById 메서드를 임시로 추가하여 생성해본 결과 `org.hibernate.LazyInitializationException` 발생

## 예상 결과
> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요
![스크린샷 2024-06-19 오후 12 43 15](https://github.com/DevCVTeam/DevCV-backend/assets/143480682/01b1c9a6-c431-41b1-a88f-31feea48e4a0)

**Comment by luxihua** [comment]
아이구야..제가 저만 편하자고 controller단에서 dto를 set했네요...죄송합니다.. 지금 수정 완료해서 다시 정상동작 확인했는데 현재 제 수정커밋이 너무 많이 쌓여있어서요..... 혹시 따로 코드 보내드리면 register 메서드 부분(controller, service, serviceImpl) 부분만 수정해서 적용 가능하실까요??

**Comment by Taehyeonn** [comment]
넵! 보내주세요

**Comment by taehyeonn** [comment]
@luxihua 넵 보내주세요!

**Comment by luxihua** [comment]
1. ResumeService.java

![image](https://github.com/DevCVTeam/DevCV-backend/assets/108069902/5b4e5cb5-1efb-4e51-9bd3-10a3db880ad5)

- 수정코드
`
  Resume register(ResumeRequest resumeRequest, MultipartFile resumeFile, List<MultipartFile> images, Long memberId);

`



2. ResumeServiceImpl.java
![image](https://github.com/DevCVTeam/DevCV-backend/assets/108069902/18c64b67-7d23-438c-bc7e-f3c66321b5e2)
![image](https://github.com/DevCVTeam/DevCV-backend/assets/108069902/da3da47d-d656-4549-98b5-8d8cce7de7f7)
![image](https://github.com/DevCVTeam/DevCV-backend/assets/108069902/db2cf92d-a723-49f4-a1df-adcead56d357)

- 수정코드

` 


       @Override
      public Resume register(ResumeRequest resumeRequest, MultipartFile resumeFile, List<MultipartFile> images, Long memberId) {

        Member member = memberRepository.findMemberBymemberid(memberId);
        if (member == null) {
            throw new MemberNotFoundException(ErrorCode.MEMBER_NOT_FOUND);
        }

        // Category 저장
        CategoryDto categoryDTO = resumeRequest.getCategory();
        List<Category> categories = categoryRepository.findByCompanyTypeAndStackType(
                categoryDTO.getCompanyType(),
                categoryDTO.getStackType()
        );
        Category category;
        if (categories.isEmpty()) {
            // 리스트가 비어 있으면 새로운 Category 생성 및 저장
            category = new Category(categoryDTO.getCompanyType(), categoryDTO.getStackType());
            category = categoryRepository.save(category);
        } else {
            // 리스트가 비어 있지 않으면 첫 번째 요소 사용
            category = categories.get(0);
        }

        // PDF 파일 업로드
        String resumeFilePath = null;
        if (resumeFile != null) {
            resumeFilePath = s3Uploader.upload(resumeFile);
            log.debug("Uploaded resume file path: {}", resumeFilePath);
        }

        if (resumeRequest.getPrice() == null || resumeRequest.getTitle() == null || resumeRequest.getContent() == null ||
                resumeRequest.getStack() == null || resumeRequest.getCategory() == null) {
            throw new HttpMessageNotReadableException(ErrorCode.EMPTY_VALUE_ERROR);
        }

        Resume resume = Resume.builder()
                .member(member)
                .price(resumeRequest.getPrice())
                .title(resumeRequest.getTitle())
                .content(resumeRequest.getContent())
                .resumeFilePath(resumeFilePath)
                .stack(resumeRequest.getStack())
                .category(category)
                .build();

        // 이미지 파일 업로드
        if (images != null && !images.isEmpty()) {
            for (int i = 0; i < images.size(); i++) {
                String imagePath = s3Uploader.upload(images.get(i));
                ResumeImage resumeImage = ResumeImage.builder()
                        .resumeImgPath(imagePath)
                        .ord(i)
                        .build();

                resume.addImage(resumeImage);
            }
        }

         //일단 임의 판매승인, 추후 관리자 mvp 완성 시 변경
         resume.setStatus(ResumeStatus.판매승인);

        // 상태 설정
        // resume.setStatus(ResumeStatus.승인대기);


        return resumeRepository.save(resume);

    }
`


3. ResumeController.java
![image](https://github.com/DevCVTeam/DevCV-backend/assets/108069902/e380e6e6-434e-49df-a636-31f7076d9232)


수정이후
`  


    Resume createdResume = resumeService.register(resumeRequest, resumeFile, images, memberId);
    ResumeDto resumeDto = ResumeDto.from(createdResume);
    return ResponseEntity.ok(resumeDto);


`

**Comment by luxihua** [comment]
다시 해보시고 문제생기면 알려주십쇼😭

**Comment by taehyeonn** [comment]
@luxihua 제가 전달을 잘못한거같네요... 결론은 ResumeResponse를 만들기 위해 resumeId로 resume를 리턴받을수있는 서비스 메서드를 요청드린거였어요..
```
public class ResumeResponse {

    ...

    public static ResumeResponse from(Resume resume) {
        return new ResumeResponse(
            ...
        );
    }
}
```

**Comment by taehyeonn** [comment]
ResumeRepository.java에 @EntityGraph 추가하여 해결했습니다(#51)
`    
//이력서 조회
    @EntityGraph(attributePaths = {"member", "category", "imageList"}, type = EntityGraph.EntityGraphType.FETCH)
    Optional<Resume> findByResumeId(Long resumeId);
`
